# Generated by Django 3.0.3 on 2021-05-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('emotion', models.CharField(max_length=100)),
                ('audio_file', models.FileField(default='', upload_to='')),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
